//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp227136
{
    using System;
    using System.Collections.Generic;
    
    public partial class ed_izms
    {
        public ed_izms()
        {
            this.materials = new HashSet<materials>();
        }
    
        public int id { get; set; }
        public string ed_izm { get; set; }
    
        public virtual ICollection<materials> materials { get; set; }
    }
}
