//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp227136
{
    using System;
    using System.Collections.Generic;
    
    public partial class materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materials()
        {
            this.product_material = new HashSet<product_material>();
        }
    
        public int id { get; set; }
        public string name_material { get; set; }
        public Nullable<int> type_material { get; set; }
        public Nullable<int> kolvo_in_paket { get; set; }
        public Nullable<int> ed_izm { get; set; }
        public Nullable<int> kolvo_on_sklad { get; set; }
        public Nullable<int> min_ostatok { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual ed_izms ed_izms { get; set; }
        public virtual type_materials type_materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_material> product_material { get; set; }
    }
}
