//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp227136
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ed_izms> ed_izms { get; set; }
        public DbSet<materials> materials { get; set; }
        public DbSet<product_material> product_material { get; set; }
        public DbSet<products> products { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<type_materials> type_materials { get; set; }
        public DbSet<type_products> type_products { get; set; }
        public DbSet<users> users { get; set; }
    }
}
