//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp227136
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demoEntities : DbContext
    {
        public demoEntities()
            : base("name=demoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ed_izms> ed_izms { get; set; }
        public virtual DbSet<materials> materials { get; set; }
        public virtual DbSet<product_material> product_material { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<type_materials> type_materials { get; set; }
        public virtual DbSet<type_products> type_products { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
