//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp227136
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.product_material = new HashSet<product_material>();
        }
    
        public int id { get; set; }
        public string name_product { get; set; }
        public Nullable<int> art { get; set; }
        public Nullable<decimal> min_price { get; set; }
        public string picture { get; set; }
        public Nullable<int> type_product { get; set; }
        public Nullable<int> kolvo_people { get; set; }
        public Nullable<int> nomer_cexa { get; set; }
    
        public virtual ICollection<product_material> product_material { get; set; }
        public virtual type_products type_products { get; set; }
    }
}
