//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp227136
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_material
    {
        public int id { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> name_material { get; set; }
        public Nullable<int> kolvo_material { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual products products { get; set; }
    }
}
